# Generated by Django 4.1.3 on 2022-11-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="img",
            field=models.ImageField(
                null=True, upload_to="products", verbose_name="Фото"
            ),
        ),
    ]
